### ISSUE TITLE
run_simulation update

### ISSUE THREAD

**Issue by zohdit** [kiarashjam/DeepJanus-BNG_with_operation#7]
In beamng_nvidia_runner, method _run_simulation:

call your methods from brewer:
brewer.setup_fog(fog_level)
brewer.setup_rain(rain_level)
...

variables fog_level, rain_level .... should added as input variable to _run_simulation(...)
and value of them should passed to _run_simulation by evaluate method

**Comment by kiarashjam** [comment]
in the previous version of the implementation , the _run_simulation just passed the node of the member to Brewer, in my implementation I send the whole member to brewer to get all information which I wanted
